name: ImageImageMatcher

pretrain_stage1: 
  model_path: 
pretrain_stage2:
  model_path:

image_extractor:
  type: superpointv1
  freeze: true 
  superpointv1:
    descriptor_dim: 256
    nms_radius: 4
    detection_threshold: 1.0  # 0.005
    detection_top_k: 1024
    remove_borders: 4
    ordering: yx
    descriptor_scale_factor: 1.0
    learnable_descriptor_scale_factor: false

matcher:
  type: LightGlue    
  freeze: false  
  max_points_num: 1024
  pad_mode: random
  desc_scale_factor: 1.0
  MNN:
    ratio_thresh: false
    distance_thresh: false
  LightGlue:
    ratio_thresh: false
    distance_thresh: false