name: test_SiLKMatcher

pretrain_stage1: 
  model_path: 
pretrain_stage2:
  model_path:

image_extractor:
  type: silk
  freeze: true 
  silk:
    padding: 1
    nms_radius: 4
    detection_threshold: 1.0
    detection_top_k: 1024
    remove_borders: 4
    descriptor_scale_factor: 1.41
    learnable_descriptor_scale_factor: false

matcher:
  type: MNN    # MNN by default
  freeze: true  # false by default
  max_points_num: 1024
  pad_mode: random
  desc_scale_factor: 1.0
  MNN:
    ratio_thresh: false
    distance_thresh: false
  LightGlue:
    ratio_thresh: false
    distance_thresh: false